# Generated by Django 5.2 on 2026-01-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('telefone', models.FloatField(blank=True, max_length=12, null=True)),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
