# Generated by Django 5.2 on 2026-01-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('data_nascimento', models.DateField(default='0000-00-00')),
                ('telefone', models.FloatField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(max_length=250)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
    ]
