# Generated by Django 5.2 on 2026-01-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taickflix', '0002_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
